services:
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    hostname: kafka
    ports:
      - '9092:9092'
      - '9093:9093'
    restart: always
    user: root
    volumes:
      - 'kafka_data:/var/lib/kafka/data'
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9093'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9094'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka:9092,CONTROLLER://kafka:9094,PLAINTEXT_HOST://0.0.0.0:9093'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_LOG_DIRS: '/var/lib/kafka/data'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - '8080:8080'
    restart: always
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      DYNAMIC_CONFIG_ENABLED: 'true'
    depends_on:
      - kafka

  postgres-marten:
    container_name: postgres-marten
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: eventstore
    ports:
      - '5433:5432'
    volumes:
      - 'marten_data:/var/lib/postgresql/data'

  postgres:
    container_name: postgres
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - db:/data/postgres

  post-cmd-api:
    build:
      context: ..
      dockerfile: SM-Post/Post.Cmd/Post.Cmd.Api/Dockerfile
    container_name: post-cmd-api
    ports:
      - '5262:5262'
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5262
      - MartenConfig__ConnectionString=Host=postgres-marten;Port=5432;Database=eventstore;Username=postgres;Password=postgres
      - ProducerConfig__BootstrapServers=kafka:9092
    depends_on:
      - postgres-marten
      - kafka
    restart: on-failure

  post-query-api:
    build:
      context: ..
      dockerfile: SM-Post/Post.Query/Post.Query.Api/Dockerfile
    container_name: post-query-api
    ports:
      - '5263:5263'
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5263
      - ConnectionStrings__PostgreSQL=Host=postgres;Port=5432;Database=SocialMedia;Username=postgres;Password=1234
      - ConsumerConfig__BootstrapServers=kafka:9092
    depends_on:
      - postgres
      - kafka
    restart: on-failure

volumes:
  kafka_data:
    driver: local
  marten_data:
    driver: local
  db:

networks:
  default:
    name: mydockernetwork
    external: true
